name: CI Build

on:
  push:
    branches:
      - githubworkflow
  pull_request:
    branches:
      - githubworkflow
permissions:
      id-token: write
      contents: read

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: 'Az CLI login'
      uses: Azure/login@v2.0.0
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          az acr login --name continuum.azurecr.io

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
          
    - name: Build Complete with Maven
      working-directory: ./complete
      run: ./mvnw --batch-mode clean package

      

 
