name: CI Build 

on:
  push:
    branches:
      - githubworkflow_old
  pull_request:
    branches:
      - githubworkflow_old
      
permissions:
      id-token: write
      contents: read

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest
    environment: QA
   
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
            
      - name: Build Complete with Maven
        working-directory: ./complete
        run: ./mvnw --batch-mode clean package

      - name: 'Az CLI login'
        uses: Azure/login@v2.0.0
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
            
      - name: 'Docker image build and Push'
        working-directory: ./complete
        run: |
            TOKEN=$(az acr login --name continuum --expose-token --output tsv --query accessToken)
            docker login continuum.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN
            docker build . -t continuum.azurecr.io/continuum/springbootmvc:${{ github.run_id }}
            docker push continuum.azurecr.io/continuum/springbootmvc:${{ github.run_id}}

          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: QA
    
    steps:
      - name: 'Az CLI login'
        uses: Azure/login@v2.0.0
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}              

      - name: Add revision to ACA
        uses: Azure/aca-review-apps@v0.2.0
        id: aca_new_revision
        with:
          resource-group: cloud-shell-storage-westus2
          name: continuum
          revision-name-suffix: ${{ env.SHORT_HASH }}
          image: continuum.azurecr.io/continuum/springbootmvc:${{ github.run_id}}
    
      - name: add new comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Revision ${{ env.CONTAINERAPP_NAME }}--${{ env.SHORT_HASH }} is created.
            ${{ steps.aca_new_revision.outputs.app-url }}
      
            


      

 
